name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (submodules + LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # Instala MÚLTIPLAS versões para cobrir exigências do projeto
      - name: Install Android packages (platforms/build-tools/NDK/CMake)
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" "platforms;android-33" \
                     "build-tools;34.0.0" "build-tools;33.0.2" \
                     "ndk;26.1.10909125" "ndk;25.2.9519653" \
                     "cmake;3.22.1" "cmake;3.18.1"

      - name: Gradle permissions
        run: chmod +x ./gradlew

      - name: Build AnkiDroid debug APK (verbose)
        run: ./gradlew :AnkiDroid:assembleDebug --stacktrace --info --no-daemon --console=plain

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnkiDroid-gamified-debug
          path: AnkiDroid/build/outputs/apk/debug/*.apk
